In [1]:
from ai_pipeline.steps.summary import _fetch_raw
from ai_pipeline.services.storage import StorageService
from ai_pipeline.programs_config.base import StorageConfig
from ai_pipeline.programs_config import load_program_config

In [6]:
cfg = load_program_config("telesales")
storage = StorageService(cfg.storage)
day="2026-03-15"

In [7]:
cfg.program_filter

['VZW Telesales']

In [8]:
import polars as pl

df = storage.read_parquet(storage.config.raw_container, f"{day}.parquet")
df.filter(pl.col("ProgramName").is_in(cfg.program_filter))

shape: (0, 48)
┌─────┬─────────────┬────────────┬─────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│     ┆ original_co ┆ contact_id ┆ mtn ┆ … ┆ program_end ┆ EmployeeID_ ┆ effective_d ┆ expiry_date │
│ --- ┆ ntact_id    ┆ ---        ┆ --- ┆   ┆ _date_right ┆ emp         ┆ ate_emp     ┆ _emp        │
│ i64 ┆ ---         ┆ str        ┆ str ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│     ┆ str         ┆            ┆     ┆   ┆ datetime[μs ┆ i64         ┆ datetime[μs ┆ datetime[μs │
│     ┆             ┆            ┆     ┆   ┆ ]           ┆             ┆ ]           ┆ ]           │
╞═════╪═════════════╪════════════╪═════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
└─────┴─────────────┴────────────┴─────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

In [14]:
df

shape: (374, 15)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ __id       ┆ contact_i ┆ totalhold ┆ totalcall ┆ … ┆ CoachID ┆ CoachName ┆ range_sta ┆ range_end │
│ ---        ┆ d         ┆ time      ┆ time      ┆   ┆ ---     ┆ ---       ┆ rt        ┆ ---       │
│ str        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ i64     ┆ str       ┆ ---       ┆ date      │
│            ┆ str       ┆ i64       ┆ i64       ┆   ┆         ┆           ┆ date      ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ 2026-03-16 ┆ f+Abl/pBp ┆ 987       ┆ 1938      ┆ … ┆ 9049922 ┆ Reyta,    ┆ 2026-02-2 ┆ 2026-05-0 │
│ 16:34:04__ ┆ UjlON5CBb ┆           ┆           ┆   ┆         ┆ Lovely Ed ┆ 3         ┆ 8         │
│ 2026-03-1… ┆ Q6+jIPWhI ┆           ┆           ┆   ┆         ┆ Lorine    ┆           ┆           │
│            ┆ gpo…      ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ 2026-03-16 ┆ B0td2qH3e ┆ 0         ┆ 572       ┆ … ┆ 9042107 ┆ Ilao,     ┆ 2026-01-0 ┆ 2026-05-0 │
│ 17:02:38__ ┆ W0s7Ax4WD ┆           ┆           ┆   ┆         ┆ Sherwin D ┆ 8         ┆ 8         │
│ 2026-03-1… ┆ qBSVcDAHn ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ l8J…      ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ 2026-03-16 ┆ KAxVLzSjZ ┆ 0         ┆ 507       ┆ … ┆ 3000658 ┆ Ramirez,  ┆ 2026-01-3 ┆ 2026-05-0 │
│ 20:16:09__ ┆ OWudYbSOK ┆           ┆           ┆   ┆         ┆ Andres R  ┆ 0         ┆ 8         │
│ 2026-03-1… ┆ 09mffOHIk ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ LFD…      ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ 2026-03-16 ┆ 3a2CgZlnp ┆ 83        ┆ 1572      ┆ … ┆ 9049922 ┆ Reyta,    ┆ 2026-02-2 ┆ 2026-05-0 │
│ 16:49:47__ ┆ zAbMZmuQj ┆           ┆           ┆   ┆         ┆ Lovely Ed ┆ 3         ┆ 8         │
│ 2026-03-1… ┆ n6R1g/asV ┆           ┆           ┆   ┆         ┆ Lorine    ┆           ┆           │
│            ┆ y4z…      ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ 2026-03-16 ┆ 8QGSYmjU0 ┆ 0         ┆ 1688      ┆ … ┆ 3000510 ┆ Rodriguez ┆ 2026-02-0 ┆ 2026-03-1 │
│ 18:52:50__ ┆ F+3574/ML ┆           ┆           ┆   ┆         ┆ , Ismael  ┆ 5         ┆ 8         │
│ 2026-03-1… ┆ eC8k40G+S ┆           ┆           ┆   ┆         ┆ F         ┆           ┆           │
│            ┆ Ion…      ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ 2026-03-16 ┆ 0S6viq8fJ ┆ 0         ┆ 809       ┆ … ┆ 3000658 ┆ Ramirez,  ┆ 2026-01-3 ┆ 2026-05-0 │
│ 19:48:29__ ┆ mSCrgVjvz ┆           ┆           ┆   ┆         ┆ Andres R  ┆ 0         ┆ 8         │
│ 2026-03-1… ┆ bM2CA169N ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ puH…      ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ 2026-03-16 ┆ opQt2lzKI ┆ 3         ┆ 424       ┆ … ┆ 9007102 ┆ Fabila,   ┆ 2025-06-0 ┆ 2026-05-0 │
│ 14:51:10__ ┆ g+OmElI0W ┆           ┆           ┆   ┆         ┆ Paula Joy ┆ 2         ┆ 8         │
│ 2026-03-1… ┆ qUMjdhwQh ┆           ┆           ┆   ┆         ┆ C         ┆           ┆           │
│            ┆ yQr…      ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ 2026-03-16 ┆ 6tnf8EBaF ┆ 178       ┆ 458       ┆ … ┆ 3000658 ┆ Ramirez,  ┆ 2026-01-3 ┆ 2026-05-0 │
│ 19:34:20__ ┆ CIwlA4kHx ┆           ┆           ┆   ┆         ┆ Andres R  ┆ 0         ┆ 8         │
│ 2026-03-1… ┆ U5UBRQwsw ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ fbI…      ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ 2026-03-16 ┆ J2SvOszAk ┆ 0         ┆ 666       ┆ … ┆ 9022739 ┆ Cruz,     ┆ 2026-01-3 ┆ 2026-05-0 │
│ 13:13:14__ ┆ gihDY87Z0 ┆           ┆           ┆   ┆         ┆ Eloisa D  ┆ 0         ┆ 1         │
│ 2026-03-1… ┆ 0I3/7ljp9 ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ BjG…      ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ 2026-03-16 ┆ NRFy5jSt5 ┆ 0         ┆ 728       ┆ … ┆ 9042107 ┆ Ilao,     ┆ 2026-01-0 ┆ 2026-05-0 │
│ 14:37:31__ ┆ 6YIjLaOPh ┆           ┆           ┆   ┆         ┆ Sherwin D ┆ 8         ┆ 8         │
│ 2026-03-1… ┆ 5uxlnWpbe ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│            ┆ GwJ…      ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘